// SPDX-License-Identifier: MIT OR Apache-2.0
//! Embed the built-in scenes (`assets/scenes/<id>/…`) into the binary.
//!
//! Every file under each scene directory becomes one `include_bytes!` entry in
//! `$OUT_DIR/builtin_scenes.rs`, so the built-in scenes work from any install
//! (deb, Flatpak, a bare downloaded binary, the browser) with no asset
//! directory to ship or locate at runtime. `src/scene/files.rs` serves them to
//! Bevy through the embedded asset source.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let root = manifest.join("../../assets/scenes");
    println!("cargo:rerun-if-changed={}", root.display());

    let mut entries: Vec<(String, String, PathBuf)> = Vec::new();
    if let Ok(dirs) = std::fs::read_dir(&root) {
        let mut dirs: Vec<PathBuf> = dirs
            .filter_map(|e| e.ok().map(|e| e.path()))
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort();
        for dir in dirs {
            let id = dir.file_name().unwrap().to_string_lossy().into_owned();
            let mut files = Vec::new();
            walk(&dir, &mut files);
            files.sort();
            for file in files {
                println!("cargo:rerun-if-changed={}", file.display());
                let rel = file
                    .strip_prefix(&dir)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                entries.push((id.clone(), rel, file));
            }
        }
    }

    let mut out = String::from(
        "/// `(scene id, path relative to the scene directory, bytes)` for every\n\
         /// file of every built-in scene. Generated by `build.rs`.\n\
         pub(crate) static BUILTIN_SCENE_FILES: &[(&str, &str, &[u8])] = &[\n",
    );
    for (id, rel, path) in &entries {
        let abs = path.canonicalize().unwrap_or_else(|_| path.clone());
        writeln!(
            out,
            "    ({id:?}, {rel:?}, include_bytes!({:?})),",
            abs.to_string_lossy()
        )
        .unwrap();
    }
    out.push_str("];\n");
    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("builtin_scenes.rs");
    std::fs::write(dest, out).unwrap();
}

/// Every regular file below `dir`, skipping dotfiles and editor droppings.
fn walk(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(read) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') || name.ends_with('~') {
            continue;
        }
        if path.is_dir() {
            walk(&path, out);
        } else if path.is_file() {
            out.push(path);
        }
    }
}
