#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Derive the Flathub-submission manifest from the in-tree one.

The manifest in this directory builds from `type: dir, path: ..`, which only
resolves inside a checkout of this repository. Flathub's buildbot checks out
only the flathub repo, so there is no `..` — a submission has to name a fixed
upstream source instead.

Rather than keep two manifests in sync by hand, this rewrites exactly one thing:
the `sources:` block, which is the last block in the file. Everything above it —
runtime version, finish-args, build-commands — is copied verbatim, so the
submitted manifest cannot drift from the one that gets built and tested locally.

    python3 flatpak/gen-flathub-manifest.py v0.4.0

Downloads the tag's tarball from GitHub to hash the exact bytes the buildbot
will fetch, rather than trusting a locally-made archive. Writes the result to
stdout unless -o is given.
"""

import argparse
import hashlib
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
MANIFEST = HERE / "io.github.dekuraan.bava.yml"
REPO = "dekuraan/bava"

# The line the in-tree sources block starts on. Everything from here down is
# replaced; the assertion below makes a layout change fail loudly rather than
# silently emit a manifest with two sources blocks or none.
SOURCES_MARKER = "    sources:\n"


def tarball_sha256(url: str) -> tuple[str, int]:
    """Stream the tarball and return (sha256, bytes). Never held in memory whole."""
    digest = hashlib.sha256()
    total = 0
    with urllib.request.urlopen(url) as response:  # noqa: S310 - fixed https URL
        while chunk := response.read(1 << 16):
            digest.update(chunk)
            total += len(chunk)
    return digest.hexdigest(), total


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tag", help="release tag to pin, e.g. v0.4.0")
    parser.add_argument("-o", "--output", type=Path, help="write here instead of stdout")
    args = parser.parse_args()

    text = MANIFEST.read_text()
    if text.count(SOURCES_MARKER) != 1:
        print(
            f"error: expected exactly one {SOURCES_MARKER.strip()!r} line in "
            f"{MANIFEST.name}; the manifest layout changed and this script needs "
            "updating.",
            file=sys.stderr,
        )
        return 1
    head, _ = text.split(SOURCES_MARKER, 1)

    url = f"https://github.com/{REPO}/archive/refs/tags/{args.tag}.tar.gz"
    print(f"hashing {url}", file=sys.stderr)
    sha, size = tarball_sha256(url)
    print(f"  {size} bytes, sha256 {sha}", file=sys.stderr)

    sources = f"""    sources:
      # Pinned to the release tag. `type: archive` strips the leading
      # `bava-{args.tag.lstrip("v")}/` component, so the build-commands above see the same
      # paths a `type: dir` build does.
      #
      # Regenerate for each release with:
      #   python3 flatpak/gen-flathub-manifest.py {args.tag}
      - type: archive
        url: {url}
        sha256: {sha}
      # Vendored crates + cargo config, generated by gen-cargo-sources.py.
      # Re-run that after *any* dependency change: Flathub builds offline, and a
      # stale list fails the build outright.
      - cargo-sources.json
"""

    out = head + sources
    if args.output:
        args.output.write_text(out)
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
