#!/usr/bin/env python3
# SPDX-License-Identifier: MIT OR Apache-2.0
"""Generate bava's app icons from one source of truth.

The artwork (deep-violet backdrop + five bloom-lit spectrum bars in the app's
cyan->magenta gradient) is drawn once in a normalised 1024x1024 body box, then
wrapped in the shape each platform wants:

  * Linux / Flathub -- full-bleed rounded square, written as a scalable SVG to
    ``flatpak/io.github.dekuraan.bava.svg`` (installed into hicolor/scalable).
  * macOS -- the Big Sur grid: an 824x824 squircle centred in a 1024 canvas
    with a drop shadow, rendered to a ``.iconset`` and packed into
    ``packaging/macos/bava.icns``.

At 16px and 32px five bars turn to mush, so those sizes get a three-bar variant
with no bloom -- same identity, legible in the Dock and the menu bar.

Usage:  python3 packaging/icon/gen-icons.py [--keep-iconset]

Needs one of ``resvg`` / ``rsvg-convert`` / ``inkscape`` / the ``cairosvg``
module on PATH. Everything else is stdlib; the ICNS container is written here
so the icon can be regenerated on Linux (``iconutil`` is macOS-only).
"""

from __future__ import annotations

import argparse
import math
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
ICON_DIR = ROOT / "packaging" / "icon"
MACOS_DIR = ROOT / "packaging" / "macos"
WEB_DIR = ROOT / "packaging" / "web"
FLATPAK_SVG = ROOT / "flatpak" / "io.github.dekuraan.bava.svg"

# Maskable PWA icons must keep their content inside a circle of 80% the canvas
# diameter; 0.78 leaves the bars comfortably inside it while still bleeding.
MASKABLE_SCALE = 0.78

SPDX = "<!-- SPDX-License-Identifier: MIT OR Apache-2.0 -->"
GENERATED = "<!-- Generated by packaging/icon/gen-icons.py; edit that, not this. -->"

# --- palette -----------------------------------------------------------------
# Matches the app's default foreground gradient and window backdrop.
BAR_LO = "#16e0ff"  # bottom of a bar
BAR_HI = "#ff36c8"  # top of a bar
BG_IN = "#241640"   # backdrop, centre
BG_OUT = "#0a0612"  # backdrop, corners

# --- geometry (normalised 1024x1024 body box) --------------------------------
# Five-bar layout: the original 128px icon scaled x8, so the identity survives.
BARS_LARGE = [  # (x, top)
    (160, 592),
    (304, 416),
    (448, 240),
    (592, 352),
    (736, 512),
]
BAR_W_LARGE, BAR_BOTTOM_LARGE = 96, 864

# Three-bar layout for <=32px: wider bars, same silhouette.
BARS_SMALL = [(168, 528), (428, 288), (688, 448)]
BAR_W_SMALL, BAR_BOTTOM_SMALL = 168, 856

CORNER_RATIO = 0.1875  # 24/128 -- the rounded square used on Linux
MACOS_BODY = 824.0     # Apple's macOS icon grid: 824 body in a 1024 canvas
SQUIRCLE_N = 5.0       # superellipse exponent; ~Apple's continuous corner
SQUIRCLE_STEPS = 256


def squircle_path(cx: float, cy: float, half: float, n: float = SQUIRCLE_N) -> str:
    """Closed superellipse path -- |x/a|^n + |y/a|^n = 1, sampled as a polyline.

    At 1024px the segments are sub-pixel, so the polyline is indistinguishable
    from the analytic curve while staying trivially correct.
    """
    pts = []
    for i in range(SQUIRCLE_STEPS):
        t = 2.0 * math.pi * i / SQUIRCLE_STEPS
        ct, st = math.cos(t), math.sin(t)
        x = cx + half * math.copysign(abs(ct) ** (2.0 / n), ct)
        y = cy + half * math.copysign(abs(st) ** (2.0 / n), st)
        pts.append(f"{x:.2f},{y:.2f}")
    return "M" + "L".join(pts) + "Z"


def _bars(small: bool) -> str:
    layout, w, bottom = (
        (BARS_SMALL, BAR_W_SMALL, BAR_BOTTOM_SMALL)
        if small
        else (BARS_LARGE, BAR_W_LARGE, BAR_BOTTOM_LARGE)
    )
    r = w / 2
    return "".join(
        f'<rect x="{x}" y="{top}" width="{w}" height="{bottom - top}" rx="{r:g}"/>'
        for x, top in layout
    )


def _filled(shape: str, fill: str) -> str:
    """Same body outline, painted — the shape doubles as clip, backdrop, sheen."""
    return shape.replace("/>", f' fill="{fill}"/>')


def build_svg(*, shape_kind: str = "rounded", small: bool = False, art_scale: float = 1.0) -> str:
    """One artwork, wrapped in the shape the platform expects.

    ``shape_kind``:
      ``rounded``  full-bleed rounded square (Linux, favicons, PWA icons)
      ``macos``    824 squircle in a 1024 canvas, drop shadow (the .icns)
      ``square``   hard-edged full bleed (apple-touch-icon, maskable PWA icon;
                   both platforms apply their own mask and hate our corners)

    ``art_scale`` shrinks the bars about the centre without shrinking the
    backdrop -- that is how the maskable icon keeps its content inside the
    80%-diameter safe circle while still bleeding to the edge.
    """
    macos = shape_kind == "macos"
    bars = _bars(small)
    if macos:
        body = MACOS_BODY
        off = (1024.0 - body) / 2.0  # 100px margin, per Apple's grid
        clip = squircle_path(512.0, 512.0, body / 2.0)
        # The artwork is authored in a 1024 box; squeeze it into the body.
        art_open = (
            f'<g filter="url(#shadow)">'
            f'<g transform="translate({off:g},{off:g}) scale({body / 1024.0:.6f})">'
        )
        art_close = "</g></g>"
        shadow = (
            '<filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">'
            '<feDropShadow dx="0" dy="24" stdDeviation="22" flood-color="#000" flood-opacity="0.28"/>'
            '<feDropShadow dx="0" dy="6" stdDeviation="6" flood-color="#000" flood-opacity="0.24"/>'
            "</filter>"
        )
        shape = f'<path d="{clip}"/>'
    else:
        art_open = art_close = ""
        shadow = ""
        rx = 0 if shape_kind == "square" else 1024 * CORNER_RATIO
        shape = f'<rect x="0" y="0" width="1024" height="1024" rx="{rx:g}"/>'

    # Bloom is bava's signature; skip it on the tiny variant where it just fogs.
    glow = (
        f'<g fill="url(#bar)" filter="url(#bloom)" opacity="0.85">{bars}</g>'
        if not small
        else ""
    )
    bloom = (
        '<filter id="bloom" x="-25%" y="-25%" width="150%" height="150%">'
        '<feGaussianBlur stdDeviation="26"/>'
        "</filter>"
        if not small
        else ""
    )
    floor = (
        '<ellipse cx="512" cy="872" rx="430" ry="46" fill="url(#floor)"/>'
        if not small
        else ""
    )
    # The top sheen is depth at 128px+ and grey fog at 16px.
    sheen = _filled(shape, "url(#sheen)") if not small else ""

    defs = [
        f'<linearGradient id="bar" x1="0" y1="1" x2="0" y2="0">'
        f'<stop offset="0" stop-color="{BAR_LO}"/>'
        f'<stop offset="1" stop-color="{BAR_HI}"/>'
        f"</linearGradient>",
        f'<radialGradient id="bg" cx="0.5" cy="0.36" r="0.78">'
        f'<stop offset="0" stop-color="{BG_IN}"/>'
        f'<stop offset="1" stop-color="{BG_OUT}"/>'
        f"</radialGradient>",
        f'<clipPath id="body">{shape}</clipPath>',
        bloom,
        shadow,
    ]
    if not small:
        defs.insert(
            2,
            '<linearGradient id="sheen" x1="0" y1="0" x2="0" y2="1">'
            '<stop offset="0" stop-color="#ffffff" stop-opacity="0.10"/>'
            '<stop offset="0.55" stop-color="#ffffff" stop-opacity="0"/>'
            "</linearGradient>"
            f'<radialGradient id="floor" cx="0.5" cy="0.5" r="0.5">'
            f'<stop offset="0" stop-color="{BAR_LO}" stop-opacity="0.30"/>'
            f'<stop offset="1" stop-color="{BAR_LO}" stop-opacity="0"/>'
            f"</radialGradient>",
        )

    lit = "\n      ".join(x for x in (floor, glow, f'<g fill="url(#bar)">{bars}</g>') if x)
    if art_scale != 1.0:
        shift = 512.0 * (1.0 - art_scale)
        lit = f'<g transform="translate({shift:g},{shift:g}) scale({art_scale:g})">{lit}</g>'

    art = [_filled(shape, "url(#bg)"), lit, sheen]
    defs_xml = "\n    ".join(d for d in defs if d)
    art_xml = "\n      ".join(a for a in art if a)

    return f"""<?xml version="1.0" encoding="UTF-8"?>
{SPDX}
{GENERATED}
<svg width="1024" height="1024" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <defs>
    {defs_xml}
  </defs>
  {art_open}<g clip-path="url(#body)">
      {art_xml}
  </g>{art_close}
</svg>
"""


# --- rendering ---------------------------------------------------------------

def _renderer() -> tuple[str, str]:
    for exe in ("resvg", "rsvg-convert", "inkscape"):
        path = shutil.which(exe)
        if path:
            return exe, path
    try:
        import cairosvg  # noqa: F401
    except ImportError:
        sys.exit(
            "error: need one of resvg / rsvg-convert / inkscape on PATH, "
            "or the cairosvg Python module"
        )
    return "cairosvg", ""


def render_png(svg: str, size: int, out: Path, renderer: tuple[str, str]) -> None:
    kind, exe = renderer
    out.parent.mkdir(parents=True, exist_ok=True)
    if kind == "cairosvg":
        import cairosvg

        cairosvg.svg2png(
            bytestring=svg.encode(), write_to=str(out),
            output_width=size, output_height=size,
        )
        return

    with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as fh:
        fh.write(svg)
        src = Path(fh.name)
    try:
        if kind == "resvg":
            cmd = [exe, "-w", str(size), "-h", str(size), str(src), str(out)]
        elif kind == "rsvg-convert":
            cmd = [exe, "-w", str(size), "-h", str(size), "-o", str(out), str(src)]
        else:  # inkscape
            cmd = [exe, str(src), "-w", str(size), "-h", str(size), "-o", str(out)]
        subprocess.run(cmd, check=True, capture_output=True)
    finally:
        src.unlink(missing_ok=True)


# --- ICNS --------------------------------------------------------------------
# (OSType, pixel size, iconset filename). Same set `iconutil -c icns` emits.
ICNS_ENTRIES = [
    ("icp4", 16, "icon_16x16.png"),
    ("ic11", 32, "icon_16x16@2x.png"),
    ("icp5", 32, "icon_32x32.png"),
    ("ic12", 64, "icon_32x32@2x.png"),
    ("ic07", 128, "icon_128x128.png"),
    ("ic13", 256, "icon_128x128@2x.png"),
    ("ic08", 256, "icon_256x256.png"),
    ("ic14", 512, "icon_256x256@2x.png"),
    ("ic09", 512, "icon_512x512.png"),
    ("ic10", 1024, "icon_512x512@2x.png"),
]


def write_icns(pngs: list[tuple[str, bytes]], out: Path) -> None:
    """Pack PNG payloads into an ICNS container (10.7+ reads PNG-in-ICNS)."""
    body = b"".join(
        ostype.encode("ascii") + struct.pack(">I", len(data) + 8) + data
        for ostype, data in pngs
    )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(b"icns" + struct.pack(">I", len(body) + 8) + body)


# --- ICO ---------------------------------------------------------------------

def write_ico(pngs: list[tuple[int, bytes]], out: Path) -> None:
    """Pack PNG payloads into an ICO container.

    PNG-in-ICO has been read by every browser since IE9/Vista, so there is no
    reason to emit the legacy BMP+AND-mask form.
    """
    count = len(pngs)
    header = struct.pack("<HHH", 0, 1, count)  # reserved, type=icon, count
    offset = len(header) + 16 * count
    entries, blobs = b"", b""
    for size, data in pngs:
        entries += struct.pack(
            "<BBBBHHII",
            size if size < 256 else 0,  # 0 encodes 256
            size if size < 256 else 0,
            0,  # palette size: 0 for truecolour
            0,  # reserved
            1,  # colour planes
            32,  # bits per pixel
            len(data),
            offset,
        )
        blobs += data
        offset += len(data)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_bytes(header + entries + blobs)


# The web manifest is emitted alongside the icons so the two can't drift.
WEBMANIFEST = """{
  "name": "bava",
  "short_name": "bava",
  "description": "A music visualizer driven by cavacore",
  "icons": [
    { "src": "icon-192.png", "sizes": "192x192", "type": "image/png" },
    { "src": "icon-512.png", "sizes": "512x512", "type": "image/png" },
    { "src": "icon-maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable" },
    { "src": "favicon.svg", "sizes": "any", "type": "image/svg+xml" }
  ],
  "theme_color": "#0a0612",
  "background_color": "#0a0612",
  "display": "fullscreen",
  "orientation": "landscape",
  "start_url": "./"
}
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--keep-iconset",
        action="store_true",
        help="also leave packaging/macos/bava.iconset/ on disk (for `iconutil` on a Mac)",
    )
    args = ap.parse_args()

    renderer = _renderer()
    print(f"renderer: {renderer[0]}")

    # 1. Sources.
    linux_svg = build_svg()
    macos_svg = build_svg(shape_kind="macos")
    macos_small_svg = build_svg(shape_kind="macos", small=True)

    ICON_DIR.mkdir(parents=True, exist_ok=True)
    (ICON_DIR / "bava.svg").write_text(linux_svg)
    (ICON_DIR / "bava-macos.svg").write_text(macos_svg)
    FLATPAK_SVG.write_text(linux_svg)
    print(f"wrote {ICON_DIR / 'bava.svg'}")
    print(f"wrote {ICON_DIR / 'bava-macos.svg'}")
    print(f"wrote {FLATPAK_SVG}")

    # 2. macOS iconset + .icns.
    iconset = MACOS_DIR / "bava.iconset"
    payloads: list[tuple[str, bytes]] = []
    for ostype, size, name in ICNS_ENTRIES:
        svg = macos_small_svg if size <= 32 else macos_svg
        png = iconset / name
        render_png(svg, size, png, renderer)
        payloads.append((ostype, png.read_bytes()))
    icns = MACOS_DIR / "bava.icns"
    write_icns(payloads, icns)
    print(f"wrote {icns} ({icns.stat().st_size / 1024:.0f} KiB, {len(payloads)} sizes)")

    # 3. Web: favicon + PWA icons for the wasm deploy.
    #    A browser tab renders favicon.svg at 16-32 CSS px, so it gets the
    #    three-bar variant -- same reasoning as the .icns small sizes.
    favicon_svg = build_svg(small=True)
    (WEB_DIR / "favicon.svg").write_text(favicon_svg)

    ico_sizes = []
    with tempfile.TemporaryDirectory() as tmp:
        for size in (16, 32, 48):
            png = Path(tmp) / f"{size}.png"
            render_png(favicon_svg, size, png, renderer)
            ico_sizes.append((size, png.read_bytes()))
    write_ico(ico_sizes, WEB_DIR / "favicon.ico")

    # iOS and Android mask the icon themselves, so hand them a hard-edged
    # square; a rounded one would show the backdrop's corners inside the mask.
    render_png(build_svg(shape_kind="square"), 180, WEB_DIR / "apple-touch-icon.png", renderer)
    render_png(linux_svg, 192, WEB_DIR / "icon-192.png", renderer)
    render_png(linux_svg, 512, WEB_DIR / "icon-512.png", renderer)
    render_png(
        build_svg(shape_kind="square", art_scale=MASKABLE_SCALE),
        512,
        WEB_DIR / "icon-maskable-512.png",
        renderer,
    )
    (WEB_DIR / "site.webmanifest").write_text(WEBMANIFEST)
    print(f"wrote {WEB_DIR}/ (favicon.svg, favicon.ico, apple-touch-icon, PWA icons, manifest)")

    # 4. A 512px preview for READMEs / the AppStream-less platforms.
    render_png(linux_svg, 512, ICON_DIR / "bava-512.png", renderer)
    print(f"wrote {ICON_DIR / 'bava-512.png'}")

    if not args.keep_iconset:
        shutil.rmtree(iconset)
    else:
        print(f"kept {iconset}")


if __name__ == "__main__":
    main()
